name: sync
on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 */12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: update submodule
        id: update-submodule
        run: |
          git submodule update --remote
      - name: Commit files
        run: |
          git config --local user.email "github-actions@omniedge.io"
          git config --local user.name "github-actions"
          git add .
          git commit -m "sync submodule" -a
          git status --porcelain=v1 2>/dev/null | wc -l
          echo ::set-output name=commit-status::$(git status --porcelain=v1 2>/dev/null | wc -l)
      - name: Push changes
        if: ${{ steps.update-submodule.outputs.commit-status==1 }}
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true

