name: omniedge test

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
  schedule:
  - cron: "0 */24 * * *"
jobs:
  
  Test-Github-Action:
    runs-on: ubuntu-22.04
    steps:
      - name: install network tools
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools
          sudo hostname omniedge

      - name: OmniEdge for Github Action
        uses: omniedgeio/github-action@v1
        with:
          securitykey: ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          virtualnetworkid: ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }}

      - name: test
        run: |
          ping -c 4 100.100.100.176
  
  Test-on-Ubuntu:
    name: Test on ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: prepare
        run: |
          sudo hostname ${{ matrix.platform }}
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools curl unzip
        
      - name: install & connect
        run: |
          curl https://omniedge.io/install/omniedge-install.sh | bash
          omniedge login -s ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          sleep 2
          sudo omniedge join -n ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }} &

      - name: test
        run: |
          ping -c 4 100.100.100.63
  Tester:
    runs-on: ubuntu-22.04
    steps:
      - name: install network tools
        run: |
          sudo hostname omniedge
      - name: OmniEdge for Github Action
        uses: omniedgeio/github-action@v1
        with:
          securitykey: ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          virtualnetworkid: ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }}

      - name: waiting for ping coming
        run: |
          sleep 100