name: omniedge test

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
  schedule:
  - cron: "0 */24 * * *"
jobs:
  
  Ping-From-Github-Action:
    runs-on: ubuntu-22.04
    steps:
      - name: install network tools
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools traceroute
          sudo hostname omniedge

      - name: OmniEdge for Github Action
        uses: omniedgeio/github-action@v1
        with:
          securitykey: ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          virtualnetworkid: ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }}

      - name: run ping and traceroute
        run: |
          sleep 30
          ping -c 4 100.100.100.34
          traceroute 100.100.100.34
  
  Ping-From-Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: prepare
        run: |
          sudo hostname ubuntu-22.04
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools curl unzip traceroute
        
      - name: install & connect
        run: |
          curl https://omniedge.io/install/omniedge-install.sh | bash
          omniedge login -s ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          sleep 2
          sudo omniedge join -n ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }} &

      - name: run ping and traceroute
        run: |
          sleep 40
          ping -c 4 100.100.100.34
          traceroute 100.100.100.34
  Tester:
    name: Tester
    runs-on: ubuntu-22.04
    outputs:
      status: ${{ steps.set-status.outputs.status }}
    steps:
      - name: prepare
        run: |
          sudo hostname Tester
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools curl unzip
        
      - name: install & connect
        run: |
          curl https://omniedge.io/install/omniedge-install.sh | bash
          omniedge login -s ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          sleep 2
          sudo omniedge join -n ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }} &
      
      - name: The connection has succeeded
        id: set-status
        run: echo "::set-output name=status::true"
      
      - name: wait 100s for ping coming
        run: |
          sleep 100