name: omniedge test

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
  schedule:
  - cron: "0 */24 * * *"
jobs:
  Tester:
    name: Tester
    runs-on: ubuntu-22.04
    outputs:
      ip4: ${{ steps.ip-address.outputs.ip-address }}
    steps:
      - name: prepare
        run: |
          sudo hostname Tester
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools curl unzip
        
      - name: install & connect
        run: |
          curl https://omniedge.io/install/omniedge-install.sh | bash
          omniedge login -s ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          sleep 2 
          sudo omniedge join -n ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }} &
      
      - name: output ip address
        id: ip-address
        run: |
          ip4=$(/sbin/ip -o -4 addr list Tester | awk '{print $4}' | cut -d/ -f1)
          echo $ip4
          echo "::set-output name=ip-address::$ip4"
      
      - name: wait 100s for ping coming
        run: |
          sleep 100
          
  Ping-From-Github-Action:
    # needs: Tester
    runs-on: ubuntu-22.04
    steps:
      - name: install network tools
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools traceroute
          sudo hostname omniedge

      - name: OmniEdge for Github Action
        uses: omniedgeio/github-action@v1
        with:
          securitykey: ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          virtualnetworkid: ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }}

      - name: run ping and traceroute
        run: |
          ping -c 4 100.100.100.34
          traceroute 100.100.100.34
  
  Ping-From-Ubuntu:
    # needs: Tester
    runs-on: ubuntu-22.04
    steps:
      - name: prepare
        run: |
          sudo hostname ubuntu-22.04
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools curl unzip traceroute
        
      - name: install & connect
        run: |
          curl https://omniedge.io/install/omniedge-install.sh | bash
          omniedge login -s ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          sleep 2
          sudo omniedge join -n ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }} &

      - name: run ping and traceroute
        run: |
          ping -c 4 100.100.100.34
          traceroute 100.100.100.34
  