name: omniedge test

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
  schedule:
  - cron: "0 */24 * * *"
jobs:
  
  Ping-From-Github-Action:
    runs-on: ubuntu-22.04
    steps:
      - name: install network tools
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools
          sudo hostname omniedge

      - name: OmniEdge for Github Action
        uses: omniedgeio/github-action@v1
        with:
          securitykey: ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          virtualnetworkid: ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }}

      - name: test
        run: |
          sleep 5
          ping -c 4 100.100.100.34
  
  Ping-From-Ubuntu:
    name: Test on ubuntu-22.04
    runs-on: ubuntu-22.04
    steps:
      - name: prepare
        run: |
          sudo hostname ubuntu-22.04
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools curl unzip
        
      - name: install & connect
        run: |
          curl https://omniedge.io/install/omniedge-install.sh | bash
          omniedge login -s ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          sleep 2
          sudo omniedge join -n ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }} &

      - name: test
        run: |
          sleep 5
          ping -c 4 100.100.100.34
  Tester:
    name: Tester
    runs-on: ubuntu-22.04
    steps:
      - name: prepare
        run: |
          sudo hostname Tester
          sudo -E apt-get -y update
          sudo -E apt-get install -y net-tools curl unzip
        
      - name: install & connect
        run: |
          curl https://omniedge.io/install/omniedge-install.sh | bash
          omniedge login -s ${{ secrets.OMNIEDGE_SECURITY_KEY }}
          sleep 2
          sudo omniedge join -n ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }} &

      - name: test
        run: |
          sleep 100